**Instructions to Follow (Failing to follow these will result mark deductions).**
1. First of all, From colab File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.
2. You can not use any built-in function except len()

3. You can not use any other python collections except array (e.g: tuple, dictionaries etc.).

4. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be 4 approaches.

 i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

 ii. arr = np.array([0] * 10) #Initializing an array length 10 with values zero.

 iii. arr = np.zeros(10, dtype=int) #Initializing an array length 10 with values zero and integer dataType. By default, dtype is float.

 iv. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.



In [2]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


# **`PART 1 TASK 1`**

In [17]:
#Assignment Part-1
#Write 3 methods and driver codes for this part.
import math
class summathidk:
  def __init__(self,array):
    self.sumlist = array

  def mean(self):
    sum = 0
    self.mean = 0
    for i in self.sumlist:
      sum+=i
    self.mean = sum/len(self.sumlist)
    return self.mean

  def standard_deviation(self):
    sum_of_standev = 0
    for i in self.sumlist:
      sum_of_standev+=(i-self.mean)**2
    self.sd = math.sqrt((sum_of_standev/(len(self.sumlist)-1)))
    sd = format(self.sd,".2f")
    return sd

  def close_number(self):
    new = np.zeros(len(self.sumlist), dtype=int)
    count = 0
    close_number1 = self.mean + 1.5*self.sd
    close_number2 = self.mean - 1.5*self.sd
    for i in range(len(self.sumlist)):
      if self.sumlist[i] >close_number1:
        new[count] = self.sumlist[i]
        count+=1
      if self.sumlist[i] <close_number2:
        new[count] = self.sumlist[i]
        count+=1
    new1 = np.zeros(count, dtype=int)
    for i in range(len(new1)):
      new1[i]=new[i]
    return new1

nums = np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
a1 = summathidk(nums)
print(a1.mean())
print(a1.standard_deviation())
print(a1.close_number())


10.181818181818182
7.96
[25 -5]


You will see the status Accepted after completion if your code is correct.

If your function is wrong you will see wrong [correction percentage]

Do not change the driver code statements. You can only change the input values to test your code.

# `**PART 2 Task 1**`

In [ ]:
#Task 01: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
  pokemon_1[pokemon_1== None]=0
  pokemon_2[pokemon_2== None]=0

  print(pokemon_1, pokemon_2)
  for x in range(len(pokemon_1)):
   pokemon_1[x]= pokemon_1[x]+ pokemon_2[len(pokemon_2)-x-1]
  return pokemon_1


print("///  Task 01: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12,3,28,-8,5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Task 01: Merge Lineup  ///
[12 3 25 1 0] [5 -9 3 0 0]
Task 1: [12 3 28 -8 5]
Not Accepted [Your output: [12 3 28 -8 5]  |  Expected Output: [12  3 28 -8  5]]
[4 5 -1 0 0] [2 27 7 12 0]
Task 1: [4 17 6 27 2]
Not Accepted [Your output: [4 17 6 27 2]  |  Expected Output: [ 4 17  6 27  2]]


In [ ]:
def analyzeHobbies(*participants):


cards = np.array([1,3,7,2,5,2,2,2,0])
returned_value = discardCards(cards, 2)

[1 3 7 0 5 2 0 2 0]
[1 3 7 5 2 2 0 0 0]


In [ ]:
# Task 02: Discard Cards
def discardCards(cards, t):
  count=0
  for i in range(len(cards)):
    if cards[i]==t:
     if count%2==0:
      cards[i]=0
     count+=1

  newarray= np.array([0]*len(cards), dtype=int)
  j=0
  for i in range(len(cards)):
    if cards[i]!=0:
      newarray[j]=cards[i]
      j+=1
  return newarray

print("///  Task 02: Discard Cards  ///")
cards = np.array([1,3,7,2,5,2,2,2,0])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1,3,7,5,2,2,0,0,0]
unittest.output_test(returned_value, np.array([1,3,7,5,2,2,0,0,0]))

cards = np.array([5,5,5,0,0])
returned_value = discardCards(cards, 5)
print(f'Task 2: {returned_value}') # This should print [5,0,0,0,0]
unittest.output_test(returned_value, np.array([5,0,0,0,0]))

///  Task 02: Discard Cards  ///
Task 2: [1 3 7 5 2 2 0 0 0]
Accepted
Task 2: [5 0 0 0 0]
Accepted


In [15]:
# Task 03: DUBER Fare Splitting
def findGroups(money, fare):

  count = 0
  for i in range(len(money)):
    for j in range(i+1,len(money)):
        if money[i]==fare:
          count+=1
          printing(count,money[i])
          money[i] = 0
          break

        elif money[i]+money[j] == fare:
          count+=1
          printing(count,money[i],money[j])
          money[j] = 0
          money[i] = 0
          break

  ungrouparena(money)

def ungrouparena(arr):
  count2 = 0
  for i in range(len(arr)):
    if arr[i]!=0:
      count2+=1
  if count2>0:
    new = np.zeros(count2,dtype=int)
    j = 0
    for i in range(len(arr)):
      if arr[i]!=0:
        new[j] = arr[i]
        j+=1
    print(f"ungrouped: ")
    for x in new:
     print(x, end=" ")

def printing(count1,elem1,elem2=None):
  if elem2!=None:
    print(f"Group{count1} : {elem1},{elem2}")
  else:
    print(f"Group{count1} : {elem1}")
print("///  Task 03: DUBER Fare Splitting  ///")
money = np.array( [120, 100, 150, 50, 30])
fare = 150
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 120, 30
# Group 2 : 100, 50
# Group 3 : 150


money = np.array( [60, 150, 60, 30, 120, 30])
fare = 180
print(f'Task 3:')
findGroups(money, fare) # This should print



///  Task 03: DUBER Fare Splitting  ///
Task 3:
Group1 : 120,30
Group2 : 100,50
Group3 : 150
Task 3:
Group1 : 60,120
Group2 : 150,30
ungrouped: 
60 30 

In [55]:
import numpy as np

# Task 04: Get Those Hobbies
def analyzeHobbies(*participants):
    # Print outputs inside the method
    count = 0
    for i in participants:
        for j in i:
            count += 1

    newarr = np.array([None] * count, dtype=object)
    x = 0

    for i in participants:
        for j in i:
            if j not in newarr:
                newarr[x] = j
                x += 1

    count1 = 0
    for r in range(len(newarr)):
        if newarr[r] is not None:
            count1 += 1

    anotherarray = np.array([None] * count1, dtype=object)
    q = 0
    for h in newarr:
        if h is not None and h not in anotherarray:
            anotherarray[q] = h
            q += 1

    print(f"Unique activities in town: {anotherarray}")

    # Print statistics
    for activity in anotherarray:
        if activity is not None:
            count2=0
            for participant in participants:
              if activity in participant:
                count2+=1
            print(f"{count2} participant(s) like(s) {activity}")

print("///  Task 04: Get Those Hobbies  ///")
participant_1 = np.array( ["Hiking", "Reading", "Photography", "Cooking"])
participant_2 = np.array( ["Reading", "Hiking", "Painting"])
participant_3 = np.array( ["Hiking", "Cooking", "Photography"])
print(f'Task 4:')
analyzeHobbies(participant_1, participant_2, participant_3) #This should print

#Unique Activities in the Town:
#['Photography', 'Painting', 'Cooking', 'Reading', 'Hiking']

#Statistics:
#2 participant(s) like(s) Photography.
#1 participant(s) like(s) Painting.
#2 participant(s) like(s) Cooking.
#2 participant(s) like(s) Reading.
#3 participant(s) like(s) Hiking.



participant_1 = np.array( ["Gardening", "Traveling"])
participant_2 = np.array( ["Singing", "Gardening", "Painting"])
print(f'Task 4:')
analyzeHobbies(participant_1, participant_2) #This should print

#Unique Activities in the Town:
#[Gardening, Traveling, Singing, Painting]

#Statistics:
#2 participant(s) like(s) Gardening.
#1 participant(s) like(s) Traveling.
#1 participant(s) like(s) Singing.
#1 participant(s) like(s) Painting.



///  Task 04: Get Those Hobbies  ///
Task 4:
Unique activities in town: ['Hiking' 'Reading' 'Photography' 'Cooking' 'Painting']
3 participant(s) like(s) Hiking.
2 participant(s) like(s) Reading.
2 participant(s) like(s) Photography.
2 participant(s) like(s) Cooking.
1 participant(s) like(s) Painting.
Task 4:
Unique activities in town: ['Gardening' 'Traveling' 'Singing' 'Painting']
2 participant(s) like(s) Gardening.
1 participant(s) like(s) Traveling.
1 participant(s) like(s) Singing.
1 participant(s) like(s) Painting.


In [ ]:
# Bonus Ungraded Task: Look and Say
def look_and_say(arr):
  #TO DO

#for later
print("///  Bonus Task: Look and Say  ///")
arr = np.array([1,3,1,1,2,2,2,1])
returned_value = look_and_say(arr)
print(f'Bonus Task: {returned_value}') # This should print [1,1,1,3,2,1,3,2,1,1]
#Hint: The size of the new array will never be more than 100.
#[You need not worry about the extra zeroes at the end of your resulting array]
