#### Part 1: Considered only one side of the distribution when finding the final range of 1.5 SD. 
#### Part 2: 
#### Task 2: After extracting the positions of the given number, you are visiting the positions alternately and then left shifting the array. But due to shifting the positions of the given number is no longer consistent with your extracted ones. Works for the given test cases but would fail generally. For example, [5,5,5,0,5]. 
#### Task 3: Missed handling some edge cases.  

**Instructions to Follow (Failing to follow these will result mark deductions).**
1. First of all, From colab File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.
2. You can not use any built-in function except len()

3. You can not use any other python collections except array (e.g: tuple, dictionaries etc.).

4. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be 4 approaches.

 i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

 ii. arr = np.array([0] * 10) #Initializing an array length 10 with values zero.

 iii. arr = np.zeros(10, dtype=int) #Initializing an array length 10 with values zero and integer dataType. By default, dtype is float.

 iv. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.



In [1]:
# You must run this cell to install dependency
# ! pip3 install fhm-unittest
# ! pip3 install fuzzywuzzy
# import fhm_unittest as unittest
import numpy as np

You will see the status Accepted after completion if your code is correct.

If your function is wrong you will see wrong [correction percentage]

Do not change the driver code statements. You can only change the input values to test your code.

In [ ]:
#Assignment Part-2
#Complete the following 4 methods(Mandatory) and one bonus(optional)task for part-2

In [55]:
#Task 01: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
  # TO DO
  pok1 = pokemon_1
  pok2 = pokemon_2
  result = np.array([0]*len(pokemon_1))

  for i in range(len(pok1)):
    if pok1[i]==None:
      result[i]+=0
    else:
      result[i]+=pok1[i]

  count= 0
  for j in range((len(pok2)-1), -1 ,-1):
    if pok2[j]==None:
      result[count]+= 0

    else:
      result[count]+=pok2[j]
    #print(result)

    count+=1

  return result



print("///  Task 01: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 1: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Task 01: Merge Lineup  ///
Task 1: [12  3 28 -8  5]
Accepted
Task 1: [ 4 17  6 27  2]
Accepted


In [9]:
# Task 02: Discard Cards
def discardCards(cards, t):
  # TO DO
  m = 0
  for i in cards:
    if i == t:
      m+= 1
  x = np.array([0]*m)

  count = 0
  for i in range(len(cards)):
    if cards[i] == t:
      x[count] = i
      count+= 1

      flag= False

  if len(x)%2 == 0:

    for j in range(0,len(x)-1,2):

      if flag == False:
        y = x[j]
        for k in range(y,(len(cards)-1)):
          cards[k],cards[k+1] = cards[k+1],0
        flag = True

      else:
        y = x[j]
        for k in range(y,len(cards)-1):
          cards[k],cards[k+1] = cards[k+1],0


  else:
    for j in range(0,len(x),2):
      if flag == False:
        y = x[j]
        for k in range(y,len(cards)-1):
          cards[k],cards[k+1] = cards[k+1],0
        flag = True

      else:
        y = x[j]-1
        for k in range(y,len(cards)-1):
          cards[k],cards[k+1] = cards[k+1],0

  return cards

print("///  Task 02: Discard Cards  ///")
cards = np.array([1,3,7,2,5,2,2,2,0])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1,3,7,5,2,2,0,0,0]
unittest.output_test(returned_value, np.array([1,3,7,5,2,2,0,0,0]))
cards = np.array([5,5,5,0,0])
returned_value = discardCards(cards, 5)
print(f'Task 2: {returned_value}') # This should print [5,0,0,0,0]
unittest.output_test(returned_value, np.array([5,0,0,0,0]))

///  Task 02: Discard Cards  ///
[3 5 6 7]
[1 3 7 2 5 2 2 2 0]
[1 3 7 5 2 2 2 0 0]
Task 2: [1 3 7 5 2 2 0 0 0]
[0 1 2]
Task 2: [5 0 0 0 0]


In [57]:
# Task 03: DUBER Fare Splitting
def findGroups(money, fare):
  # TO DO
  grp = ""
  count = 1
  for i in range(len(money)):
    sum = money[i]
    if sum == fare:
      print(f"Group: {count}: {sum}")
      money[i] = 0
      count+=1


    else:
      for j in range(i+1,len(money)):

          sum= money[i]+money[j]
          if sum == fare:
            print(f"Group: {count}: {money[i]},  {money[j]}")
            money[i] = 0
            money[j] = 0
            count+=1
            break


  for k in range(len(money)):
    if money[k]!=0:
      grp+= f"{money[k]} "

  if len(grp)>0:
    print(f"Ungrouped: { grp } ")

  # Print outputs inside the method

print("///  Task 03: DUBER Fare Splitting  ///")
money = np.array( [120, 100, 150, 50, 30])
fare = 150
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 120, 30
# Group 2 : 100, 50
# Group 3 : 150


money = np.array( [60, 150, 60, 30, 120, 30])
fare = 180
print(f'Task 3:')
findGroups(money, fare) # This should print

# Group 1 : 60, 120
# Group 2 : 30, 150
# Ungrouped : 30 60

///  Task 03: DUBER Fare Splitting  ///
Task 3:
Group: 1: 120,  30
Group: 2: 100,  50
Group: 3: 150
Task 3:
Group: 1: 60,  120
Group: 2: 150,  30
Ungrouped: 60 30  


In [58]:
# Task 04: Get Those Hobbies
def analyzeHobbies(* participants): #(* arguments) is used for variable number of parameters
  # TO DO
  import numpy as np

  # Print outputs inside the method
  unique_hobbies=""
  hobbies=""
  for i in participants:
    for h in i:
      if h not in unique_hobbies:
        unique_hobbies += h + ","
      hobbies += h + ","
  unique_hobbies = unique_hobbies[:-1]
  hobbies = hobbies[:-1]
  unique_hobbies_array = unique_hobbies.split(",")
  hobbies_array = hobbies.split(",")
  print("Unique Activities in the Town:")
  print(unique_hobbies_array)
  print("Statistics:")
  for h in unique_hobbies_array:
      count = 0
      for i in range(len(hobbies_array)):
        if hobbies_array[i] == h:
          count += 1
      print(f"{count} participant(s) like(s) {h}.")
  # Print outputs inside the method



print("///  Task 04: Get Those Hobbies  ///")
participant_1 = np.array( ["Hiking", "Reading", "Photography", "Cooking"])
participant_2 = np.array( ["Reading", "Hiking", "Painting"])
participant_3 = np.array( ["Hiking", "Cooking", "Photography"])
print(f'Task 4:')
analyzeHobbies(participant_1, participant_2, participant_3) #This should print

#Unique Activities in the Town:
#['Photography', 'Painting', 'Cooking', 'Reading', 'Hiking']

#Statistics:
#2 participant(s) like(s) Photography.
#1 participant(s) like(s) Painting.
#2 participant(s) like(s) Cooking.
#2 participant(s) like(s) Reading.
#3 participant(s) like(s) Hiking.



participant_1 = np.array( ["Gardening", "Traveling"])
participant_2 = np.array( ["Singing", "Gardening", "Painting"])
print(f'Task 4:')
analyzeHobbies(participant_1, participant_2) #This should print

#Unique Activities in the Town:
#[Gardening, Traveling, Singing, Painting]

#Statistics:
#2 participant(s) like(s) Gardening.
#1 participant(s) like(s) Traveling.
#1 participant(s) like(s) Singing.
#1 participant(s) like(s) Painting.


///  Task 04: Get Those Hobbies  ///
Task 4:
Unique Activities in the Town:
['Hiking', 'Reading', 'Photography', 'Cooking', 'Painting']
Statistics:
3 participant(s) like(s) Hiking.
2 participant(s) like(s) Reading.
2 participant(s) like(s) Photography.
2 participant(s) like(s) Cooking.
1 participant(s) like(s) Painting.
Task 4:
Unique Activities in the Town:
['Gardening', 'Traveling', 'Singing', 'Painting']
Statistics:
2 participant(s) like(s) Gardening.
1 participant(s) like(s) Traveling.
1 participant(s) like(s) Singing.
1 participant(s) like(s) Painting.


In [ ]:
# Bonus Ungraded Task: Look and Say
def look_and_say(arr):
  #TO DO


print("///  Bonus Task: Look and Say  ///")
arr = np.array([1,3,1,1,2,2,2,1])
returned_value = look_and_say(arr)
print(f'Bonus Task: {returned_value}') # This should print [1,1,1,3,2,1,3,2,1,1]
#Hint: The size of the new array will never be more than 100.
#[You need not worry about the extra zeroes at the end of your resulting array]


For Assignment Part-1, you can create new code cells in the below and write your codes there. Also you should write driver codes to test your code for part-1.

In [ ]:
#Assignment Part-1
#Write 3 methods and driver codes for this part.

In [63]:
def mean(array):
  sum = 0
  count = 0
  while count!= len(array):
    sum+= array[count]
    count+= 1
  mean = sum/count
  return mean

def standard_deviation(array,mean):
  new_array = np.zeros(2,int)
  count = 0
  sum = 0
  while count!= len(array):
    sum+= (array[count]-mean)**2
    count+=1
  sum= (sum/(len(array)-1))**(1/2)
  j = 0

  for i in range(len(array)):
    if (array[i]-mean)>= 1.5*sum:
      new_array[j]=array[i]
      j+=1
  return f"The standard deviation is: {sum.round(2)}\nNew array: {new_array}"

x=np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
mean = mean(x)
print(mean)
print(standard_deviation(x,mean))

10.181818181818182
The standard deviation is: 7.96
New array: [25  0]
