In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [ ]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))



Task 1: Zigzag Walk

In [ ]:
def walk_zigzag(floor):
  row,col = floor.shape
  idx = 0

  for i in range(col):
    if i % 2 == 0:
      for j in range(idx,row,2):
        print(floor[j][i], end=' ')
        idx = row - 2
      print()
    else:
      if row % 2 != 0:
        for j in range(idx,-1,-2):
          print(floor[j][i], end=' ')
          idx = 0
        print()

      else:
        idx = row - 1
        for j in range(idx, 0 , -2):
          print(floor[j][i], end=' ')
        print()
        idx = 0



floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )



print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

[['3' '8' '4' '6' '1']
 ['7' '2' '1' '9' '3']
 ['9' '0' '7' '5' '8']
 ['2' '1' '3' '4' '0']
 ['1' '4' '2' '8' '6']]
Walking Sequence:
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 
################
[['3' '8' '4' '6' '1']
 ['7' '2' '1' '9' '3']
 ['9' '0' '7' '5' '8']
 ['2' '1' '3' '4' '0']]
Walking Sequence:
3 9 
1 2 
4 7 
4 9 
1 8 


Task 2: Row Rotation Policy of BRACU Classroom

In [ ]:
def row_rotation(exam_week, seat_status):
  row,col = floor.shape
  idx = 0

  for i in range(col):
    if i % 2 == 0:
      for j in range(idx,row,2):
        print(floor[j][i], end=' ')
        idx = row - 2
      print()
    else:
      if row % 2 != 0:
        for j in range(idx,-1,-2):
          print(floor[j][i], end=' ')
          idx = 0
        print()

      else:
        idx = row - 1
        for j in range(idx, 0 , -2):
          print(floor[j][i], end=' ')
        print()
        idx = 0


seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

|  A  |  B  |  C  |  D  |  E  |
-------------------------------
|  F  |  G  |  H  |  I  |  J  |
-------------------------------
|  K  |  L  |  M  |  N  |  O  |
-------------------------------
|  P  |  Q  |  R  |  S  |  T  |
-------------------------------
|  U  |  V  |  W  |  X  |  Y  |
-------------------------------
|  Z  |  AA |  BB |  CC |  DD |
-------------------------------

3 9 
1 2 
4 7 
4 9 
1 8 
Your friend AA will be on row None


Task 3: Matrix Manipulation

In [ ]:
import numpy as np
def reverse_Matrix(matrix):
    r,c=matrix.shape
    r_m=np.zeros((r,c),dtype=int)
    for i in range(r):
        for j in range(c):
            r_m[i][j]=matrix[r-1-i][c-1-j]
    return r_m
    for i in matrix:
        for j in i:
            print(f"{j:3}", end=" ")
        print("|")

matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
print_matrix(matrix)
print('################')
print()
reversed_matrix = reverse_Matrix(matrix)
print_matrix(reversed_matrix)

#This should print
#|  6  |  13 |  10 |  2  |
#-------------------------
#|  4  |  1  |  3  |  9  |
#-------------------------
#|  13  |  13  |  8 |  9 |
#-------------------------
#|  4 |  0  |  8  |  14  |
#-------------------------


[[14  8  0  4]
 [ 9  8 13 13]
 [ 9  3  1  4]
 [ 2 10 13  6]]
################

[[ 6 13 10  2]
 [ 4  1  3  9]
 [13 13  8  9]
 [ 4  0  8 14]]


Task 4: Chess Piece

In [ ]:
def show_knight_move(knight):
    rows, cols = 8, 8
    chessboard = ""

    for i in range(rows):
        for j in range(cols):
            diff_row = knight[0] - i
            diff_col = knight[1] - j

            if (i, j) == knight:
                chessboard += "| 66 "
            elif (diff_row == 2 and diff_col == 1) or \
                 (diff_row == 1 and diff_col == 2) or \
                 (diff_row == -2 and diff_col == 1) or \
                 (diff_row == -1 and diff_col == 2) or \
                 (diff_row == 2 and diff_col == -1) or \
                 (diff_row == 1 and diff_col == -2) or \
                 (diff_row == -2 and diff_col == -1) or \
                 (diff_row == -1 and diff_col == -2):
                chessboard += "| 3 "
            else:
                chessboard += "| 0 "
        chessboard += "|\n" + "-" * (6 * cols + 1) + "\n"

    return chessboard

def print_matrix(chessboard):
    print(chessboard)


knight = (3,4)
chess_board = show_knight_move(knight)
print_matrix(chess_board)
#This Should print
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 66 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#-----------------------------------------

| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 0 | 66 | 0 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
-------------------------------------------------



Task 5: Matrix Compression

In [ ]:
def compress_matrix(mat):
    rows = len(matrix)
    cols = len(matrix[0])
    compressed_matrix = ""


    for i in range(0, rows, 2):
        for j in range(0, cols, 2):
            block_sum = matrix[i][j] + matrix[i][j+1] + matrix[i+1][j] + matrix[i+1][j+1]
            compressed_matrix += f"| {block_sum} "
        compressed_matrix += "|\n" + "-" * (6 * (cols // 2) - 1) + "\n"

    return compressed_matrix


matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print_matrix(matrix)
print('################')
print()
returned_array=compress_matrix(matrix)
print_matrix(returned_array)
#This should print
#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  3  5  2]
 [-2  0  6 -3]]
################

| 14 | 22 |
-----------
| 2 | 10 |
-----------



Task 6: Game Arena

In [ ]:
def play_game(arena):
    total_points = 0
    rows = len(arena)
    cols = len(arena[0])

    for i in range(rows):
        for j in range(cols):
            if arena[i][j] % 50 == 0 and arena[i][j]!=0:
                points_from_surrounding = 0
                if i > 0 and arena[i-1][j] == 2:
                    points_from_surrounding += 1
                if i < rows - 1 and arena[i+1][j] == 2:
                    points_from_surrounding += 1
                if j > 0 and arena[i][j-1] == 2:
                    points_from_surrounding += 1
                if j < cols - 1 and arena[i][j+1] == 2:
                    points_from_surrounding += 1
                total_points += points_from_surrounding * 2

    return total_points

def game_result(arena):
    total_points = play_game(arena)
    if total_points >= 10:
        return f"Points Gained: {total_points}. Your team has survived the game."
    else:
        return f"Points Gained: {total_points}. Your team is out."

arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 6. Your team is out.

print(".....................")
arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 14. Your team has survived the game.

[[  0   2   2   0]
 [ 50   1   2   0]
 [  2   2   2   0]
 [  1 100   2   0]]
.....................
[[  0   2   2   0   2]
 [  1  50   2   1 100]
 [  2   2   2   0   2]
 [  0 200   2   0   0]]


14

Bonus Task: Primary vs Secondary Diagonal

In [ ]:
def check_diagonal(matrix1, matrix2):
  #TO DO

array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])

check_Diagonal(array1, array2) #This should print YES
print(".............")
array1 = np.array([[0, 9, 9, 1], [9, 0, 2, 9], [9, 3, 0, 9], [4, 9, 9, 0]])
array2 = np.array([[4, 9, 9, 0], [9, 0, 3, 9], [9, 0, 2, 9], [0, 9, 5, 1]])

check_Diagonal (array1, array2) #This should print NO
