#### Task 2: Number of rotations should be exam_week - 1.
#### Task 3: Missing. 
#### Task 4: Exact copy with ID: 20301402
#### Task 5: Missing. 
#### Bonus Task: The order also matters. 

In [4]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))



Task 1: Zigzag Walk

In [7]:
def walk_zigzag(floor):
  #TO DO
  rw,cl=floor.shape
  for i in range(0,cl):
    if rw%2==0:
      if i%2==0:
        for j in range(0,rw,2):
          output1=floor[j][i]
          print(output1,end=' ')
        print()
      else:
        for j in range(rw-1,0,-2):
          output2=floor[j][i]
          print(output2,end=' ')
        print()
    else:
      if i%2==0:
        for j in range(0,rw,2):
          output3=floor[j][i]
          print(output3,end=' ')
        print()
      else:
        for j in range(rw-2,0,-2):
          output4=floor[j][i]
          print(output4,end=' ')
        print()

floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
|  1  |  4  |  2  |  8  |  6  |
-------------------------------
Walking Sequence:
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 
################
|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
Walking Sequence:
3 9 
1 2 
4 7 
4 9 
1 8 


Task 2: Row Rotation Policy of BRACU Classroom

In [20]:
def row_rotation(exam_week, seat_status):
  #To Do
  rw,cl=seat_status.shape
  for i in range(0,exam_week):
    arr=np.array(seat_status[rw-1])
    for j in range(rw-1,0,-1):
      seat_status[j]=seat_status[j-1]
    seat_status[0]=arr
  for x in range(rw):
    for y in range(cl):
     if seat_status[x][y]=='AA':
       return f"{seat_status}\n Your friend AA will be on row {x}."

seat_status = np.array([[ 'A' , 'B' , 'C' , 'D' , 'E'],
                  ['F' , 'G' , 'H' , 'I' , 'J'],
                  ['K' , 'L' , 'M' , 'N' , 'O'],
                  ['P' , 'Q' , 'R' , 'S' , 'T'],
                  ['U' , 'V' , 'W' , 'X' , 'Y'],
                  ['Z' , 'AA' , 'BB' , 'CC' , 'DD']])
exam_week=3
print_matrix(seat_status)
print()
row_number=row_rotation(exam_week, seat_status) #This should print modified seat status after rotation
print(f'Your friend AA will be on row {row_number}') #This should print Your friend AA will be on row 2

[['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']
 ['P' 'Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']]

Your friend AA will be on row [['P' 'Q' 'R' 'S' 'T']
 ['U' 'V' 'W' 'X' 'Y']
 ['Z' 'AA' 'BB' 'CC' 'DD']
 ['A' 'B' 'C' 'D' 'E']
 ['F' 'G' 'H' 'I' 'J']
 ['K' 'L' 'M' 'N' 'O']]
 Your friend AA will be on row 2.


Task 3: Matrix Manipulation

In [ ]:
def reverse_Matrix(matrix):
  #TO DO


matrix = np.array([
[14,  8,  0,  4],
[9,  8,  13,  13],
[9,  3,  1,  4],
[2,  10,  13,  6]
])
print_matrix(matrix)
print('################')
print()
reversed_matrix = reverse_Matrix(matrix)
print_matrix(reversed_matrix)

#This should print
#|  6  |  13 |  10 |  2  |
#-------------------------
#|  4  |  1  |  3  |  9  |
#-------------------------
#|  13  |  13  |  8 |  9 |
#-------------------------
#|  4 |  0  |  8  |  14  |
#-------------------------


Task 4: Chess Piece

In [18]:
def show_knight_move(knight):
  #To Do
  rows, cols = 8, 8
  chess_board = ""

  for i in range(rows):
        for j in range(cols):
            diff_row = knight[0] - i
            diff_col = knight[1] - j

            if (i, j) == knight:
                chess_board += "| 66 "
            elif (diff_row == 2 and diff_col == 1) or \
                 (diff_row == 1 and diff_col == 2) or \
                 (diff_row == -2 and diff_col == 1) or \
                 (diff_row == -1 and diff_col == 2) or \
                 (diff_row == 2 and diff_col == -1) or \
                 (diff_row == 1 and diff_col == -2) or \
                 (diff_row == -2 and diff_col == -1) or \
                 (diff_row == -1 and diff_col == -2):
                chess_board += "| 3 "
            else:
                chess_board += "| 0 "
        chess_board += "|\n" + "-" * (6 * cols + 1) + "\n"

  return chess_board
def print_matrix(chessboard):
    print(chessboard)





knight = (3,4)
chess_board = show_knight_move(knight)
print_matrix(chess_board)
#This Should print
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 66 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#------------------------------------------
#| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
#-----------------------------------------

| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 0 | 66 | 0 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 3 | 0 | 0 | 0 | 3 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 3 | 0 | 3 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
-------------------------------------------------
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
-------------------------------------------------



Task 5: Matrix Compression

In [ ]:


def compress_matrix(mat):
    #TO DO

matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [1,3,5,2],
                 [-2,0,6,-3]
                 ])
print_matrix(matrix)
print('################')
print()
returned_array=compress_matrix(matrix)
print_matrix(returned_array)
#This should print
#|  14  |  22 |
#--------------
#|  2  |  10  |
#--------------

Task 6: Game Arena

In [19]:
def play_game(arena):
  #TO DO
  rw,cl=arena.shape
  total=0
  for i in range(rw):
    for j in range(cl):
      if arena[i][j]%50==0 and arena[i][j]>=50:
        if i!=rw-1 and arena[i+1][j]:
           total+=1
        if   i!=0 and arena[i-1][j]==2:
            total+=1
        if j!=cl-1 and arena[i][j+1]==2:
            total+=1
        if   j!=0 and arena[i][j-1]==2:
           total+=1



  sum=(total)*2
  print('Points Gained:',sum,end=' ')
  if sum<10:
    print('.Your team is out.')
  else:
    print('.Your team has survived the game.')




arena=np.array([[0,2,2,0],
                [50,1,2,0],
                [2,2,2,0],
                [1,100,2,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 6. Your team is out.

print(".....................")
arena=np.array([[0,2,2,0,2],
                [1,50,2,1,100],
                [2,2,2,0,2],
                [0,200,2,0,0]
                ])
print_matrix(arena)
play_game(arena)
#This should print
#Points Gained: 14. Your team has survived the game.

[[  0   2   2   0]
 [ 50   1   2   0]
 [  2   2   2   0]
 [  1 100   2   0]]
Points Gained: 6 .Your team is out.
.....................
[[  0   2   2   0   2]
 [  1  50   2   1 100]
 [  2   2   2   0   2]
 [  0 200   2   0   0]]
Points Gained: 14 .Your team has survived the game.


Bonus Task: Primary vs Secondary Diagonal

In [9]:
def check_diagonal(matrix1, matrix2):
  #TO DO
  row1,col1=matrix1.shape
  row2,col2=matrix2.shape
  sum=0
  sum1=0
  for i in range(row1):
    for j in range(col1):
      if i+j==col1-1:
        sum+=matrix1[i][j]
  for i in range(row2):
    for j in range(col2):
      if i==j:
        sum1+=matrix2[i][j]
  if sum==sum1:
    print('YES')
  else:
    print('NO')
array1 = np.array([[0, 4, 1], [7, 2, 5], [3, 6, 0]])
array2 = np.array([[3, 6, 0], [5, 2, 7], [0, 4, 1]])

check_diagonal(array1, array2) #This should print YES
print(".............")
array1 = np.array([[0, 9, 9, 1], [9, 0, 2, 9], [9, 3, 0, 9], [4, 9, 9, 0]])
array2 = np.array([[4, 9, 9, 0], [9, 0, 3, 9], [9, 0, 2, 9], [0, 9, 5, 1]])

check_diagonal (array1, array2) #This should print NO


YES
.............
NO
